"""Human Review Queue service — evidence-based finding adjudication.

Provides the review queue, file context classification, adjudication
persistence, and review summary. All mutations are append-only.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import PurePosixPath
from typing import Any

from sqlalchemy.orm import Session
from sqlalchemy import func

from ..models import (
    Finding, Repository, FindingAdjudication, MissionFindingLink,
    Mission, JournalEvent, ScanJob,
)


# ---------------------------------------------------------------------------
# File context classification
# ---------------------------------------------------------------------------

FILE_CONTEXT_PRODUCTION = "PRODUCTION"
FILE_CONTEXT_TEST = "TEST"
FILE_CONTEXT_FIXTURE = "FIXTURE"
FILE_CONTEXT_GENERATED = "GENERATED"
FILE_CONTEXT_VENDOR = "VENDOR"
FILE_CONTEXT_CONFIGURATION = "CONFIGURATION"
FILE_CONTEXT_DOCUMENTATION = "DOCUMENTATION"
FILE_CONTEXT_UNKNOWN = "UNKNOWN"

_TEST_PATTERNS = re.compile(
    r"(^tests?/|/tests?/|_test\.py$|_test\.js$|_test\.ts$|"
    r"\.test\.(py|js|ts|tsx|jsx)$|test_/|/test_|"
    r"^test/|/test/|_spec\.(js|ts|jsx|tsx)$|"
    r"__tests__/|\.spec\.(py|js|ts|tsx|jsx)$)",
    re.IGNORECASE,
)

_FIXTURE_PATTERNS = re.compile(
    r"(fixtures?/|__fixtures?__/|testdata/|test_data/|mocks?/|__mocks?__/)",
    re.IGNORECASE,
)

_GENERATED_PATTERNS = re.compile(
    r"(\.generated\.|__pycache__|node_modules/|dist/|build/|\.min\.(js|css)|"
    r"_pb2\.py$|_pb2_grpc\.py$|\.autogenerated)",
    re.IGNORECASE,
)

_VENDOR_PATTERNS = re.compile(
    r"(vendor/|third_party/|external/|\.vendor/)",
    re.IGNORECASE,
)

_CONFIG_PATTERNS = re.compile(
    r"(package\.json$|pyproject\.toml$|setup\.cfg$|setup\.py$|"
    r"Cargo\.toml$|go\.mod$|pom\.xml$|build\.gradle$|"
    r"Makefile$|CMakeLists\.txt$|\.eslintrc|\.prettierrc|"
    r"tsconfig\.json$|webpack\.config|babel\.config|"
    r"Dockerfile$|docker-compose|\.env\.)",
    re.IGNORECASE,
)

_DOCS_PATTERNS = re.compile(
    r"(\.md$|\.rst$|\.txt$|docs?/|CHANGELOG|README|LICENSE|CONTRIBUTING|"
    r"SECURITY|CODE_OF_CONDUCT)",
    re.IGNORECASE,
)


def classify_file_context(file_path: str) -> str:
    """Classify a file path into its operational context."""
    if not file_path:
        return FILE_CONTEXT_UNKNOWN

    path = PurePosixPath(file_path)
    parts = [p.lower() for p in path.parts]

    if _DOCS_PATTERNS.search(file_path):
        return FILE_CONTEXT_DOCUMENTATION
    if _FIXTURE_PATTERNS.search(file_path):
        return FILE_CONTEXT_FIXTURE
    if _GENERATED_PATTERNS.search(file_path):
        return FILE_CONTEXT_GENERATED
    if _VENDOR_PATTERNS.search(file_path):
        return FILE_CONTEXT_VENDOR
    if _CONFIG_PATTERNS.search(file_path):
        return FILE_CONTEXT_CONFIGURATION
    if _TEST_PATTERNS.search(file_path):
        return FILE_CONTEXT_TEST

    return FILE_CONTEXT_PRODUCTION


# ---------------------------------------------------------------------------
# Threshold exceedance ratio
# ---------------------------------------------------------------------------

def compute_exceedance_ratio(observed_lines: int, threshold: int) -> float:
    if threshold <= 0:
        return 0.0
    return round(observed_lines / threshold, 2)


def classify_exceedance_tier(ratio: float) -> str:
    if ratio < 1.1:
        return "NEAR_THRESHOLD"
    if ratio < 2.0:
        return "MODERATE_EXCEEDANCE"
    if ratio < 5.0:
        return "HIGH_EXCEEDANCE"
    return "EXTREME_EXCEEDANCE"


# ---------------------------------------------------------------------------
# Observation / Concern / Actionability inference
# ---------------------------------------------------------------------------

def infer_observation_status(finding: Finding) -> str:
    meta = finding.metadata_json or {}
    evidence = meta.get("evidence_references", [])
    if evidence:
        return "SUPPORTED"
    if finding.description:
        return "SUPPORTED"
    return "UNSUPPORTED"


def infer_concern_status(finding: Finding, file_context: str) -> str:
    if file_context == FILE_CONTEXT_TEST:
        return "INSUFFICIENT"
    if file_context in (FILE_CONTEXT_GENERATED, FILE_CONTEXT_VENDOR):
        return "NOT_MEANINGFUL"
    meta = finding.metadata_json or {}
    evidence = meta.get("evidence_references", [])
    if not evidence:
        return "INSUFFICIENT"
    return "POSSIBLE"


def infer_actionability_status(
    finding: Finding, file_context: str, exceedance_ratio: float | None
) -> str:
    if file_context == FILE_CONTEXT_TEST:
        if exceedance_ratio and exceedance_ratio >= 5.0:
            return "NEEDS_MORE_EVIDENCE"
        return "NOT_ACTIONABLE"
    if file_context in (FILE_CONTEXT_GENERATED, FILE_CONTEXT_VENDOR):
        return "NOT_ACTIONABLE"
    if exceedance_ratio is not None and exceedance_ratio < 1.1:
        return "NEEDS_MORE_EVIDENCE"
    return "NEEDS_MORE_EVIDENCE"


# ---------------------------------------------------------------------------
# Review queue construction
# ---------------------------------------------------------------------------

def _extract_line_count(finding: Finding) -> int | None:
    meta = finding.metadata_json or {}
    evidence = meta.get("evidence_references", [])
    for e in evidence:
        detail = e.get("detail", "")
        m = re.search(r"(\d+)\s*lines", detail)
        if m:
            return int(m.group(1))
    return None


def build_review_queue(
    db: Session,
    repository_id: str | None = None,
    severity: str | None = None,
    category: str | None = None,
    reviewed: bool | None = None,
    limit: int = 50,
    offset: int = 0,
) -> list[dict[str, Any]]:
    q = db.query(Finding)
    if repository_id:
        q = q.filter(Finding.repository_id == repository_id)
    if severity:
        q = q.filter(Finding.severity == severity)
    if category:
        q = q.filter(Finding.category == category)

    findings = q.order_by(Finding.severity, Finding.id).all()

    repo_cache: dict[str, Repository] = {}
    scan_cache: dict[str, ScanJob | None] = {}
    items = []
    for f in findings:
        repo = repo_cache.get(f.repository_id)
        if not repo:
            repo = db.query(Repository).filter(Repository.id == f.repository_id).first()
            if repo:
                repo_cache[f.repository_id] = repo

        if f.repository_id not in scan_cache:
            scan_cache[f.repository_id] = (
                db.query(ScanJob)
                .filter(
                    ScanJob.repository_id == f.repository_id,
                    ScanJob.status == "completed",
                )
                .order_by(ScanJob.completed_at.desc())
                .first()
            )
        scan = scan_cache[f.repository_id]

        file_context = classify_file_context(f.module or "")
        line_count = _extract_line_count(f)
        threshold = 300
        exceedance = compute_exceedance_ratio(line_count, threshold) if line_count else None

        latest_adj = (
            db.query(FindingAdjudication)
            .filter(FindingAdjudication.finding_id == f.id)
            .order_by(FindingAdjudication.reviewed_at.desc())
            .first()
        )

        mission_links = (
            db.query(MissionFindingLink)
            .filter(MissionFindingLink.finding_id == f.id)
            .all()
        )
        mission_ids = [ml.mission_id for ml in mission_links]

        meta = f.metadata_json or {}
        gov_decisions = meta.get("governance_decision", {})

        item = {
            "finding_id": meta.get("finding_id", f.id),
            "db_id": f.id,
            "scan_id": scan.id if scan else None,
            "commit_sha": scan.commit_sha if scan else None,
            "repository_id": f.repository_id,
            "repository_name": repo.name if repo else "UNKNOWN",
            "severity": f.severity,
            "category": f.category,
            "title": f.title,
            "description": f.description or "",
            "module": f.module or "",
            "file_context": file_context,
            "line_count": line_count,
            "exceedance_ratio": exceedance,
            "exceedance_tier": classify_exceedance_tier(exceedance) if exceedance else None,
            "evidence_references": meta.get("evidence_references", []),
            "governance_decision": meta.get("governance_decision", {}).get("decision", "N/A"),
            "governance_rationale": meta.get("governance_decision", {}).get("rationale", ""),
            "observation_status": infer_observation_status(f),
            "concern_status": infer_concern_status(f, file_context),
            "actionability_status": infer_actionability_status(f, file_context, exceedance),
            "mission_linkage": mission_ids if mission_ids else "UNVERIFIED_LEGACY_LINKAGE",
            "current_adjudication": latest_adj.classification if latest_adj else None,
            "operator": latest_adj.operator if latest_adj else None,
            "operator_notes": latest_adj.operator_notes if latest_adj else None,
            "reviewed_at": latest_adj.reviewed_at.isoformat() if latest_adj else None,
        }
        items.append(item)

    total = len(items)
    filtered = items[offset:offset + limit]
    return {"items": filtered, "total": total, "limit": limit, "offset": offset}


# ---------------------------------------------------------------------------
# Adjudication persistence (append-only)
# ---------------------------------------------------------------------------

def create_adjudication(
    db: Session,
    finding_id: str,
    classification: str,
    operator: str,
    notes: str | None = None,
    trial_id: str | None = None,
    scan_id: str | None = None,
    governance_decision_at_review: str | None = None,
    *,
    policy_suppressed: bool = False,
    suppression_rule_id: str | None = None,
    suppression_rule_version: str | None = None,
) -> FindingAdjudication:
    """Append-only human adjudication (authoritative system of record).

    Human authority only: the operator is required. For deterministic policy
    suppression, policy_suppressed=True with a suppression_rule_id is recorded
    (kept distinct from human NOT_ACTIONABLE) and remains auditable.
    """
    finding = db.query(Finding).filter(Finding.id == finding_id).first()
    if not finding:
        raise ValueError(f"Finding {finding_id} not found")

    meta = finding.metadata_json or {}
    file_context = classify_file_context(finding.module or "")
    line_count = _extract_line_count(finding)
    threshold = 300
    exceedance = compute_exceedance_ratio(line_count, threshold) if line_count else None

    if policy_suppressed and suppression_rule_id:
        operator = f"POLICY:{suppression_rule_id}"

    adjudication = FindingAdjudication(
        finding_id=finding_id,
        repository_id=finding.repository_id,
        scan_id=scan_id,
        trial_id=trial_id,
        classification=classification,
        observation_status=infer_observation_status(finding),
        concern_status=infer_concern_status(finding, file_context),
        actionability_status=infer_actionability_status(finding, file_context, exceedance),
        file_context=file_context,
        exceedance_ratio=exceedance,
        operator=operator,
        operator_notes=notes,
        reviewed_at=datetime.now(timezone.utc),
        evidence_snapshot=meta.get("evidence_references", []),
        governance_decision_at_review=governance_decision_at_review or meta.get("governance_decision", {}).get("decision", ""),
        related_mission_ids=[],
        schema_version="1.0",
        policy_suppressed=policy_suppressed,
        suppression_rule_id=suppression_rule_id,
        suppression_rule_version=suppression_rule_version,
    )
    db.add(adjudication)
    db.commit()
    db.refresh(adjudication)
    return adjudication


def get_adjudications_for_finding(db: Session, finding_id: str) -> list[FindingAdjudication]:
    return (
        db.query(FindingAdjudication)
        .filter(FindingAdjudication.finding_id == finding_id)
        .order_by(FindingAdjudication.reviewed_at.desc())
        .all()
    )


# ---------------------------------------------------------------------------
# Review summary
# ---------------------------------------------------------------------------

def get_review_summary(db: Session, trial_id: str | None = None) -> dict[str, Any]:
    q = db.query(FindingAdjudication)
    if trial_id:
        q = q.filter(FindingAdjudication.trial_id == trial_id)

    adjudications = q.all()
    total = len(adjudications)

    counts: dict[str, int] = {}
    for a in adjudications:
        counts[a.classification] = counts.get(a.classification, 0) + 1

    useful = counts.get("USEFUL", 0)
    fp = counts.get("FALSE_POSITIVE", 0)
    not_action = counts.get("NOT_ACTIONABLE", 0)
    needs_ev = counts.get("NEEDS_MORE_EVIDENCE", 0)
    dup = counts.get("DUPLICATE", 0)
    unknown = counts.get("UNKNOWN", 0)

    classifiable = total - dup
    finding_precision = useful / classifiable if classifiable > 0 else None
    actionability_rate = useful / total if total > 0 else None

    return {
        "total_reviewed": total,
        "useful": useful,
        "false_positive": fp,
        "not_actionable": not_action,
        "needs_more_evidence": needs_ev,
        "duplicate": dup,
        "unknown": unknown,
        "finding_precision": finding_precision,
        "actionability_rate": actionability_rate,
    }


def get_pending_count(db: Session) -> int:
    reviewed_ids = (
        db.query(FindingAdjudication.finding_id)
        .distinct()
        .subquery()
    )
    return db.query(Finding).filter(~Finding.id.in_(reviewed_ids)).count()


# ---------------------------------------------------------------------------
# Deterministic policy suppression (Post Cycle 8)
# Kept distinct from human NOT_ACTIONABLE. Auditable + recoverable.
# ---------------------------------------------------------------------------

def apply_deterministic_suppression(
    db: Session,
    finding_id: str,
    suppression_rule_id: str,
    reason: str,
    rule_version: str = "1.0",
    notes: str | None = None,
) -> FindingAdjudication:
    """Machine-authoritative but NON-actionability suppression.

    Records a distinct, auditable adjudication (policy_suppressed=True) that
    prevents mission generation without pretending a human decided
    NOT_ACTIONABLE. The finding remains visible/recoverable for review.
    """
    adj = create_adjudication(
        db,
        finding_id=finding_id,
        classification="SUPPRESSED_BY_POLICY",
        operator="",  # set to POLICY:<rule_id> inside create_adjudication
        notes=notes or reason,
        policy_suppressed=True,
        suppression_rule_id=suppression_rule_id,
        suppression_rule_version=rule_version,
    )
    _emit_journal_event(
        db,
        event_type="policy.suppression",
        stage="evidence_risk_gate",
        repository_id=adj.repository_id,
        payload={
            "finding_id": finding_id,
            "suppression_rule_id": suppression_rule_id,
            "rule_version": rule_version,
            "reason": reason,
            "adjudication_id": adj.id,
        },
        actor=f"POLICY:{suppression_rule_id}",
    )
    return adj


def list_suppressions(
    db: Session,
    repository_id: str | None = None,
) -> list[dict[str, Any]]:
    q = db.query(FindingAdjudication).filter(
        FindingAdjudication.policy_suppressed.is_(True)
    )
    if repository_id:
        q = q.filter(FindingAdjudication.repository_id == repository_id)
    rows = q.order_by(FindingAdjudication.reviewed_at.desc()).all()
    return [
        {
            "adjudication_id": r.id,
            "finding_id": r.finding_id,
            "suppression_rule_id": r.suppression_rule_id,
            "rule_version": r.suppression_rule_version,
            "operator": r.operator,
            "notes": r.operator_notes,
            "reviewed_at": r.reviewed_at.isoformat() if r.reviewed_at else None,
        }
        for r in rows
    ]


# ---------------------------------------------------------------------------
# Mission ↔ Finding explicit linkage
# ---------------------------------------------------------------------------

def create_mission_finding_link(
    db: Session,
    mission_id: str,
    finding_id: str,
    repository_id: str | None = None,
    relationship_type: str = "PRIMARY",
) -> MissionFindingLink:
    existing = (
        db.query(MissionFindingLink)
        .filter(
            MissionFindingLink.mission_id == mission_id,
            MissionFindingLink.finding_id == finding_id,
        )
        .first()
    )
    if existing:
        return existing

    link = MissionFindingLink(
        mission_id=mission_id,
        finding_id=finding_id,
        repository_id=repository_id,
        relationship_type=relationship_type,
    )
    db.add(link)
    db.commit()
    db.refresh(link)
    return link


def get_mission_links(db: Session, mission_id: str) -> list[MissionFindingLink]:
    return (
        db.query(MissionFindingLink)
        .filter(MissionFindingLink.mission_id == mission_id)
        .all()
    )


def get_finding_mission_links(db: Session, finding_id: str) -> list[MissionFindingLink]:
    return (
        db.query(MissionFindingLink)
        .filter(MissionFindingLink.finding_id == finding_id)
        .all()
    )


# ---------------------------------------------------------------------------
# Journal event emission
# ---------------------------------------------------------------------------

def _emit_journal_event(
    db: Session,
    event_type: str,
    stage: str,
    repository_id: str | None,
    payload: dict[str, Any],
    actor: str = "operator",
) -> JournalEvent:
    # Use the canonical payload hash from evosia.journal_models so the
    # stored payload_sha256 is verifiable by JournalEvent.verify_integrity()
    # (which calls the same _canonical_payload_sha256). Mixing a different
    # hash function/truncation here broke journal integrity verification.
    from evosia.journal_models import _canonical_payload_sha256
    payload_sha = _canonical_payload_sha256(payload)
    import uuid as _uuid
    event = JournalEvent(
        event_id=f"evt-{_uuid.uuid4().hex[:12]}",
        timestamp=datetime.now(timezone.utc).isoformat(),
        event_type=event_type,
        stage=stage,
        repository_id=repository_id,
        actor=actor,
        payload=payload,
        payload_sha256=payload_sha,
    )
    db.add(event)
    db.commit()
    return event


def emit_finding_reviewed(
    db: Session,
    finding_id: str,
    repository_id: str | None,
    classification: str,
    operator: str,
    notes: str | None,
    adjudication_id: str,
    trial_id: str | None = None,
) -> JournalEvent:
    return _emit_journal_event(
        db,
        event_type="finding.reviewed",
        stage="human_review",
        repository_id=repository_id,
        payload={
            "finding_id": finding_id,
            "classification": classification,
            "operator": operator,
            "notes": notes,
            "adjudication_id": adjudication_id,
            "trial_id": trial_id,
        },
        actor=operator,
    )


def emit_finding_reclassified(
    db: Session,
    finding_id: str,
    repository_id: str | None,
    classification: str,
    operator: str,
    previous_adjudication_id: str | None,
    notes: str | None,
    adjudication_id: str,
    trial_id: str | None = None,
) -> JournalEvent:
    return _emit_journal_event(
        db,
        event_type="finding.reclassified",
        stage="human_review",
        repository_id=repository_id,
        payload={
            "finding_id": finding_id,
            "classification": classification,
            "operator": operator,
            "previous_adjudication_id": previous_adjudication_id,
            "notes": notes,
            "adjudication_id": adjudication_id,
            "trial_id": trial_id,
        },
        actor=operator,
    )
